id: P007916
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2730
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་
  author: ''
  volumes:
    9a9d003b7ecb480aa3e2da6767179212:
      image_group_id: I1CZ2734
      title: ''
      volume_number: 1
      total_pages: 940
ebook_metadata:
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་
  author: ''
  sku: P007916
  cover: cover.jpg
  layers:
  - pagination
