id: P007916
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ2730
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་
  author: ''
  volumes:
    125b879e58504ad9930ec01b2c18c529:
      image_group_id: I1CZ2734
      title: Volume 1 of lam rim bla ma brgyud pa'i rnam thar
      volume_number: 1
      total_pages: 940
      base_file: v001.txt
