id: I40F0A174
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:25:19+00:00'
last_modified: '2022-06-09T07:27:09.791362+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2730
  title: ལམ་རིམ་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '7353':
      image_group_id: I1CZ2734
      title: Volume 1 of lam rim bla ma brgyud pa'i rnam thar
      total_pages: 940
      order: 1
      base_file: 7353.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
